Update assurance-exchange-data-resiliency.md
MicrosoftDocs/Compliance pull request #5
Opened 2020-12-02 21:48 UTC by msbemba

added an important note about in place hold

2020-12-02 21:48 UTC, msbemba commented
Isue#https://github.com/MicrosoftDocs/microsoft-365-docs/issues/3567

2020-12-02 21:48 UTC, msbemba commented
@JohanFreelancer9 please copy review

2020-12-03 04:08 UTC, JohanFreelancer9 commented on compliance/assurance/assurance-exchange-data-resiliency.md
> +>  As we continue to invest in different ways to preserve mailbox content, we're announcing the retirement of In-Place Holds in the Exchange admin center (EAC) in Exchange Online. Starting July 1, 20
```suggestion
>  As we continue to invest in different ways to preserve mailbox content, we're announcing the retirement of In-Place Holds in the Exchange admin center (EAC) in Exchange Online. Starting July 1, 2020, you won't be able to create new In-Place Holds. But you'll still be able to manage In-Place Holds in the EAC or by using the **Set-MailboxSearch** cmdlet in Exchange Online PowerShell. However, starting October 1, 2020, you won't be able to manage In-Place Holds. You'll only be able to remove them in the EAC or by using the **Remove-MailboxSearch** cmdlet. Using In-Place Holds in Exchange Server and Exchange hybrid deployments will still be supported. For more information about the retirement of In-Place Holds in Exchange Online, see [Retirement of legacy eDiscovery tools](https://docs.microsoft.com/microsoft-365/compliance/legacy-ediscovery-retirement).
```

2020-12-03 04:13 UTC, JohanFreelancer9 commented on compliance/assurance/assurance-exchange-data-resiliency.md
> +An In-Place Hold preserves all mailbox content, including deleted items and original versions of modified items. All such mailbox items are returned in an [In-Place eDiscovery](in-place-ediscovery/in
```suggestion
An In-Place Hold preserves all mailbox content, including deleted items and original versions of modified items. All such mailbox items are returned in an [In-Place eDiscovery](in-place-ediscovery/in-place-ediscovery.md) search. When you place an In-Place Hold on a user's mailbox, the contents in the corresponding archive mailbox (if it's enabled) are also placed on hold and returned in an eDiscovery search.
```

2020-12-03 04:25 UTC, JohanFreelancer9 requested changes
Copy review.

2020-12-03 09:58 UTC, JohanFreelancer9 approved these changes

2020-12-10 18:17 UTC, merged